  spring.devtools.livereload.enabled=true
  debug: false
    
    management.endpoints.web.exposure.include:"*"
  logging:
    level:
      com.example.boardService: debug
      com.springframework.web.servlet: debug
      com.hibernate.type.descriptor.sql.BasicBinder: trace


  spring:
    datasource:
      url: jdbc:mysql://localhost:3306/boardweb
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
      defer-datasource-initialization: trye
      hibernate:
        ddl-auto: create
      open-in-view: false
      show-sql: true
      properties:
        hibernate.format_sq: true
        hibernate.default_batch_fetch_size: 100

    h2:
      console:
        enabled: false
    sql:
      init:
        mode: always

    data.reset:

